CVSRCS_ID           := "$$Name:  $$ $$Id: Makefile,v 1.4 2012/07/27 20:41:25 peachey Exp $$"

#$(info $$Name:  $$ $$Id: Makefile,v 1.4 2012/07/27 20:41:25 peachey Exp $$)

HD_COMPONENT_NAME	= astroh

HD_COMPONENT_VERS	=

HD_INC_SUBDIR		= ahsgd

HD_INSTALL_HEADERS	= ahSGDtyps.h

include ${HD_STD_MAKEFILE}
