CVSRCS_ID           := "$$Name:  $$ $$Id: Makefile,v 1.4 2012/07/27 20:41:24 peachey Exp $$"

#$(info $$Name:  $$ $$Id: Makefile,v 1.4 2012/07/27 20:41:24 peachey Exp $$)

HD_COMPONENT_NAME		= astroh

HD_COMPONENT_VERS		= 

HD_SUBDIRS			    = ahhxi src

HD_TEST_SUBDIRS			= src/test

include ${HD_STD_MAKEFILE}
