CVSRCS_ID           := "$$Name:  $$ $$Id: Makefile,v 1.4 2012/07/27 20:42:30 peachey Exp $$"

#$(info $$Name:  $$ $$Id: Makefile,v 1.4 2012/07/27 20:42:30 peachey Exp $$)

HD_COMPONENT_NAME		= astroh

HD_COMPONENT_VERS		= 

HD_SUBDIRS			    = hxisgdsff

HD_TEST_SUBDIRS			= ${HD_SUBDIRS}

include ${HD_STD_MAKEFILE}
