CVSRCS_ID           := "$$Name:  $$ $$Id: Makefile,v 1.4 2012/07/27 20:41:24 peachey Exp $$"

#$(info $$Name:  $$ $$Id: Makefile,v 1.4 2012/07/27 20:41:24 peachey Exp $$)

HD_COMPONENT_NAME	= astroh

HD_COMPONENT_VERS	=

HD_INC_SUBDIR		= ahhxi

HD_INSTALL_HEADERS	= ahHXItyps.h

include ${HD_STD_MAKEFILE}
